### ISSUE TITLE
Tracing / Blame Accuracy

### ISSUE THREAD

**Issue by joeyrosztoczy** [keathley/norm#12]
@keathley your talk inspired me to think about how ad-hoc contracts between web based services can be (even when formalized abstractly by something like JSON API or GraphQL etc).

One of the most powerful uses of something like `conform/2` to me would be at the web-service input / boundary layer like a Phoenix Controller. It would be a super-powered feature to be able to do something like:

```elixir
with {:ok, data} <- conform_specificied_param_cast(params) do
...
end
```

where `conform/2` could return something easily matchable + semantically meaningful to a fallback controller or error handling path for users / systems.

Was curious if you've considered "blame/tracing" like features (don't like blame but is center in the WHIP paper) such as appending meta data like an atom name of a defined spec's predicate that failed, or allowing options into conform that could manually tag failures on the `{:error, _}` return to make parsing or pattern matching easy on end users.

I would be really interested in trying to contribute a feature like that if you thought it was valuable!

**Comment by keathley** [comment]
Norm now returns errors as datastructures so it should now be possible to build these sorts of operations.
