### ISSUE TITLE
Specifying that a value in a map or struct can be nil

### ISSUE THREAD

**Issue by marcelotto** [keathley/norm#17]
It doesn't seem to be possible to specify that a value in map or struct can also be `nil`:

```elixir
conform(%{foo: nil}, schema(%{foo: spec(is_binary() or is_nil())}))
# => {:error, ["val: %{foo: nil} in: :foo fails: :required"]}
```

Am I missing something or is this a bug?

**Comment by keathley** [comment]
This looks like a bug to me.

**Comment by keathley** [comment]
I've published a new version which should fix this.
