### ISSUE TITLE
Collections on selectors

### ISSUE THREAD

**Issue by matreyes** [keathley/norm#28]
Great work! 

I'm trying to validate collections of maps `coll_of()` based on selections, for example

````elixir
  conform(%{a: [%{b: true}], 
    selection(
        schema(%{a: 
          one_of(
            schema(%{b: spec(is_boolean())})
            )
          }
        ),
        [a: [:b]]
    )
  )
```` 
but selections doesn't allows collections.
It's there a workaround?

**Comment by keathley** [comment]
Hmmm am I correct in thinking you want a schema like this?

```elixir
schema(%{
  a: coll_of(
    schema(%{
      b: spec(is_boolean())
    })
  )
})
```

I'm not sure if we have a good way to support this without nesting the selections themselves like so:

```elixir
    selection(
        schema(%{a: 
          coll_of(
            selection(schema(%{b: spec(is_boolean())}), [:b])
            )
          }
        ),
        [:a]
    )
```
This should work but its definitely not super ergonomic. I'll try to see if I can think through a better way to support selections on collections since that seems like a very common use case.

**Comment by matreyes** [comment]
Cool!, 

I like the solution, it's explicit. 
The problem is that when you run the conform() function, if there are errors on the nested document (collection), it only returns that (nested) errors. It should merge the errors with the parent's.

**Comment by keathley** [comment]
@matreyes I think I see what you're saying but could you give me a concrete example? I think the errors returned by `coll_of` might need to be improved but I haven't found a really good example yet.

**Comment by matreyes** [comment]
sure, so let's keep the example

````elixir
sch = selection(
  schema(
    %{a: coll_of(selection(schema(%{b: spec(is_boolean())}), [:b])), 
    c: spec(is_boolean())}
  ),
  [:c]
)
# case 1
> conform(%{a: [%{b: true}], c: false}, sch)
{:ok, %{a: [%{b: true}], c: false}}

# case 2
> conform(%{a: [%{b: true}]}, sch)
{:error, [%{input: %{a: [%{b: true}]}, path: [:c], spec: ":required"}]}

# case 3
> conform(%{a: [%{b: "no_bool"}]}, sch)
{:error, [%{input: "no_bool", path: [:a, 0, :b], spec: "is_boolean()"}]}
````
I would expect that the case 3 should return both errors for `:c` and `:b` 

````elixir
> conform(%{a: [%{b: "no_bool"}]}, sch)
{:error, [
    %{input: "no_bool", path: [:a, 0, :b], spec: "is_boolean()"},
    %{input: %{a: [%{b: true}]}, path: [:c], spec: ":required"}
]}
````

**Comment by keathley** [comment]
I've fixed the issue that was causing the required error to not be returned from the selection. I'm going to continue thinking through the rest of this. Thanks for providing the example! That was very helpful in tracking this down.
