### ISSUE TITLE
Proposal to make parameter names in a @contract optional

### ISSUE THREAD

**Issue by asianfilm** [keathley/norm#35]
One currently has to name each parameter in a contract, but the name doesn't have to match those used in the function.

For example:

```elixir
defmodule Test do
  use Norm
  
  def age(), do spec(is_integer())
  def name(), do: spec(is_binary())
  def greeting(), do: spec(is_binary())
	
  @contract hello(name :: name(), age :: age()) :: greeting()
  def hello(name, age), do: "Hello #{name}. You are #{age}!"
end
```

(Excuse the "looseness" of the `spec` definitions above; in use, I'd be more explicit with the use of regular expressions.)

In the example above, we have the contract:
```elixir
@contract hello(name :: name(), age :: age()) :: greeting()
```

The repetition, if one is naming specs semantically, can make it a little less readable and a little more error-prone.

We can currently write a slightly cleaner:
```elixir
@contract hello(n :: name(), a :: age()) :: greeting()
```

But we can't do the following, which in retrospect might confuse the intent since we're not ignoring the spec, only the parameter name:
```elixir
@contract hello(_ :: name(), _ :: age()) :: greeting()
```

It gives the following error:
```elixir
** (CompileError) invalid use of _. "_" represents a value to be ignored in a pattern and cannot be used in expressions
```

---
What I'd prefer is an option to write:
```elixir
@contract hello(name(), age()) :: greeting()
```

For me, this more concise notation encourages semantically richer naming of specs that communicate their intent better. Of course, there will be those who abuse the shorthand, but they're the same coders who will have lazy parameter names.

This is perhaps a little more controversial, but since `@contract` must be specified immediately above the function(s) it defines, one could conceivably drop the function name:

```elixir
@contract (name(), age()) :: greeting()
```

Or, if it does look a bit like function currying, which Elixir doesn't support without third-party libraries, the even cleaner:

```elixir
@contract name() :: age() :: greeting()
```

I do copy and paste contracts between functions, and sometimes forget to rename them.

---
Note that I'd still like the option to have parameter names in my contracts. I sometimes like to arrange my contract parameters vertically over several lines. And I often use semi-generic naming.

For example (with the necessary module, spec and schema definitions), this is valid code:

```elixir
@contract complex_image_processing_function(
  poster :: Image.s(),
  stills :: coll_of(Image.s()),
  perceptual_hashes :: coll_of(hash()),
  md5s :: coll_of(hash())
) :: coll_of(Image.s())
def complex_image_processing_function(poster, stills, perceptual_hashes, md5s), do: ...  
```

**Comment by wojtekmach** [comment]
Yes, the name of the arguments in the contract doesn't matter, only the position. My original thinking was the name could later be be used to provide better error messages but that hasn't been done yet. Worth mentioning that `@contract` intentionally looks similar to `@spec`, and because the latter allows skipping the argument name, doing it in the contract is a +1 from me. If you want to give a shot at implementing it, this should be a matter of just loosening up this case: https://github.com/keathley/norm/blob/v0.10.2/lib/norm/contract.ex#L104.

**Comment by asianfilm** [comment]
Thanks, Wojtek (@wojtekmach).

Since Chris (@keathley) is currently focusing on improving the error messages, maybe it's best to wait a while to see what he can pull off. Then again, maybe it's good enough for an error to say, "there's an issue with the second parameter...", rather than "there's an issue with the `age` parameter...".

Following the look of `@spec` makes a lot of sense, including keeping the function name.

**Comment by wojtekmach** [comment]
forgot to mention, there's an open PR https://github.com/keathley/norm/pull/29 that refactors and enhances contracts so any changes in this area should probably wait on that one anyway.

**Comment by keathley** [comment]
I'm definitely +1 on making the argument names optional. I'm not focused on that at the moment so if we want to do it as part of the refactors in #29 that's good with me. Otherwise, we can plan that work for the future.
