### ISSUE TITLE
0 Cost Abstractions

### ISSUE THREAD

**Issue by joeyrosztoczy** [keathley/norm#9]
This might be super naive, but looking to start a discussion -

I'm wondering if there's a way to make norm a zero cost abstraction (in production), or to include that idea a part of a roadmap for norm.

I don't think its an MVP needed feature, but for big systems at scale (where inter-service smart contracts seem to provide significant value), it could be a huge bonus.

Would it be possible, for example, to inject specs and or conform functions via macro's in just a test or dev environment, and not in production or a remote?

Curious if you've given any thought to it @keathley

**Comment by keathley** [comment]
I've thought about this some. I think it makes a lot of sense to remove any preconditions or postconditions when running in production. But I'm not sure that makes as much sense for functions like `conform!` or `valid?`. In my experience, having the ability to call those functions wherever you see fit is a huge benefit. We'll often call `conform!` directly after an API call like so:

```elixir
defmodule User do
  def s, do: schema(%{
    "name" => spec(is_binary() and (& &1 != "")),
    "email" => spec(is_binary() and (& &1 =~ @email_regex))
  })
end

def result(spec), do: one_of([
  {:ok, spec},
  {:error, spec(is_binary())}
])

def get_user(id) do
  ids
  |> get("/user/#{id}")
  |> conform!(result(User.s()))
end
```

We want to do the call to `conform!` even in production. That way, we return only the specified keys. So while I think it makes sense to remove preconditions and postconditions, I don't think we'd want to strip all occurrences of `conform` or anything like that.

We could potentially have an alternative to `conform!` such as `assert!` that we _could_ strip out. But I haven't thought through the implications of that decision, and for now, I think stripping the contract annotations should do most of what people need to do.

**Comment by joeyrosztoczy** [comment]
Yeah that makes a ton of sense - conform is super useful for control flow like a changeset, and we'd want to to pass the value on if it does conform or handle the error (especially if its a user or data effecting error in the app, or we need to communicate the violation to the upstream service). Sweet, thanks for sharing!
