### ISSUE TITLE
Introductory documentation seems incorrect, and broken in places

### ISSUE THREAD

**Issue by alexslade** [keathley/norm#91]
I picked up Norm and started following through the examples in IEx (elixir 1.10), and some of the first code samples don't work. There are also a few errors/typos. 

1. The `gen` example doesn't work. 

I'm getting the following error 
```
** (Protocol.UndefinedError) protocol Norm.Generatable not implemented for #Norm.Schema<%{user: #Norm.Schema<%{age: #Norm.Spec<is_integer() and &(&1 > 0)>, name: #Norm.Spec<is_binary()>}>}> of type Norm.Core.Schema (a struct). This protocol is implemented for the following type(s): Norm.Generator
```

2. The provided gen example doesn't seem to make sense. It implies that an age of `-2` is valid, when the schema defines age as being an integer greater than 0. Is that intentional? 

3. This line is missing a closing `}`
```
input = %{user: %{name: "chris", age: 30, email: "c@keathley.io"}
```

4. The return on the conform example doesn't exactly match what you actually get back. 
```
input = %{user: %{name: "chris", age: 30, email: "c@keathley.io"}
conform!(input, user_schema)
=> %{user: %{age: 30, email: "c@keathley.io", name: "chris"}} 
```

Am I doing something stupid here, or do the docs need updating?

**Comment by keathley** [comment]
Thanks @alexslade. The README has been updated. In order to use `gen` you'll also need to make sure stream_data is included in your dependencies.
