### ISSUE TITLE
Selection with all keys is inherited by child schema

### ISSUE THREAD

**Issue by lud** [keathley/norm#97]
With this norm code:

```elixir
defmodule Test do
  use Norm

  def validate(data) do
    child_schema =
      schema(%{
        x: spec(is_integer()),
        y: spec(is_integer())
      })

    parent_schema =
      selection(
        schema(%{
          a: spec(is_integer()),
          b: child_schema
        })
      )

    conform!(data, parent_schema)
  end
end
```

And this data:

```elixir
Test.validate(%{a: 1, b: %{}})
```

I have the following error.
```
** (Norm.MismatchError) Could not conform input:
val: %{} in: :b/:x fails: :required
val: %{} in: :b/:y fails: :required
```

This looks incorrect to me, as I do not call `selection()` on the `child_schema` so I expect its keys not to be required. Is it a bug or is it the expected behaviour ?

Thank you.

**Comment by lud** [comment]
I can see in the docs that `selection` can indeed get the keys for the children schemas:

```elixir
selection(user_schema, [user: [:age]])
```

But should it be inherited when calling `selection/1` and not `selection/2` ?

**Comment by keathley** [comment]
If no keys are provided than `selection/1` will recursively mark all keys in all schemas as required. It does not overwrite any existing selections though. If you only want to require `a` and `b` then you can do something like this: ```
parent_schema =
      selection(
        schema(%{
          a: spec(is_integer()),
          b: child_schema
        }),
        [:a, :b]
      )
```

**Comment by lud** [comment]
Ok so explicitly list all 0-level keys then.

Thank you
